<a href="https://colab.research.google.com/github/damiangonzaleznaval2im21-hash/Notebooks/blob/main/CuadernoCursoAnalisisDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
numeros = [2,4,6,8,10]
numeros, type(numeros)

([2, 4, 6, 8, 10], list)

In [3]:
serie = pd.Series(numeros)
serie, type(serie)

(0     2
 1     4
 2     6
 3     8
 4    10
 dtype: int64,
 pandas.core.series.Series)

In [4]:
import random

nombres_base = ["Ana", "Pedro", "Juan", "Joseline", "Luis", "Maria", "Carlos", "Sofia"]
ciudades_base = ["Paris", "CDMX", "Roma", "Barcelona", "Berlin", "Tokyo"]
edades_base = [18, 20, 22, 25, 30, 35, 40, 42]

datos = {
    "Nombres": [random.choice(nombres_base) for _ in range(100)],
    "Edad": [random.choice(edades_base) for _ in range(100)],
    "Ciudad": [random.choice(ciudades_base) for _ in range(100)]
}

In [5]:
df = pd.DataFrame(data = datos)
df[(df['Edad'] < 30) & (df['Ciudad'] == "CDMX")]

   Nombres  Edad Ciudad
10    Juan    20   CDMX
14    Juan    20   CDMX
31   Sofia    20   CDMX
70    Juan    25   CDMX
75  Carlos    18   CDMX
86  Carlos    22   CDMX
94  Carlos    20   CDMX

Exportar Data Frame en csv

In [6]:
df.to_csv("DataframePersonas")

Importar DataFrame a partir de csv

In [7]:
productsdf = pd.read_csv("products-1000.csv",index_col=0)
productsdf

,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
Index,,,,,,,,,,,,
1,Thermostat Drone Heater,Consumer approach woman us those star.,Bradford-Yu,Kitchen Appliances,74,USD,139,8619793560985,Orchid,Medium,backorder,38
2,Ultra Speaker Iron Grill Advanced One,Point suggest easy money operation could white.,Douglas Group,Fitness Equipment,510,USD,351,3057216124300,MediumSeaGreen,Small,backorder,27
3,Watch Headphones Kettle,Reach husband education.,Landry-Austin,Beauty & Personal Care,254,USD,409,9825254410556,Lavender,XXL,pre_order,2
4,Portable Toaster Clock Monitor Silent,Always choose school poor table main.,"Odom, Norton and Foster",Makeup,69,USD,119,9490814777808,Pink,XL,in_stock,94
5,Pro Toaster Oven,Worry put discuss easy back too career.,"Fowler, Mendoza and Mcdaniel",Automotive,525,USD,727,4726650403799,LightCoral,XL,in_stock,95
...,...,...,...,...,...,...,...,...,...,...,...,...
996,Silent Router Phone Portable Automatic,Piece the fight near never once bank.,Huffman Group,Toys & Games,903,USD,737,8227581307423,MediumAquaMarine,XL,limited_stock,33
997,Digital Treadmill Clean Go,Apply drive outside reach apply.,Woodward Group,Toys & Games,8,USD,330,522633507294,PaleVioletRed,Medium,out_of_stock,9
998,Wireless Vacuum Shaver,Line cup course student each about.,Ramos-Cardenas,Beauty & Personal Care,615,USD,630,1892829625606,PaleVioletRed,Extra Large,pre_order,4
999,Portable Cooker Brush 360 Digital Mini,History feel worry painting only power bad.,Hooper-Bender,Men's Clothing,811,USD,566,1683591150065,LightGreen,S,in_stock,65
1000,Smart Watch Edge Digital Sense,Pay image either rest.,Campos Inc,Kitchen Appliances,867,USD,769,8697154897673,Gainsboro,50x70 cm,limited_stock,10

MANIPULACION DE DATOS CON PANDAS

In [8]:
nombres_productos = productsdf["Name"]
nombres_productos

Index
1                      Thermostat Drone Heater
2        Ultra Speaker Iron Grill Advanced One
3                      Watch Headphones Kettle
4        Portable Toaster Clock Monitor Silent
5                             Pro Toaster Oven
                         ...
996     Silent Router Phone Portable Automatic
997                 Digital Treadmill Clean Go
998                     Wireless Vacuum Shaver
999     Portable Cooker Brush 360 Digital Mini
1000            Smart Watch Edge Digital Sense
Name: Name, Length: 1000, dtype: object

Más de una columna

In [9]:
colum = ["Name","Stock","Price"]
productsdf[colum]

                                         Name  Stock  Price
Index
1                     Thermostat Drone Heater    139     74
2       Ultra Speaker Iron Grill Advanced One    351    510
3                     Watch Headphones Kettle    409    254
4       Portable Toaster Clock Monitor Silent    119     69
5                            Pro Toaster Oven    727    525
...                                       ...    ...    ...
996    Silent Router Phone Portable Automatic    737    903
997                Digital Treadmill Clean Go    330      8
998                    Wireless Vacuum Shaver    630    615
999    Portable Cooker Brush 360 Digital Mini    566    811
1000           Smart Watch Edge Digital Sense    769    867

[1000 rows x 3 columns]

In [10]:
#Vamos a seleccionar filas por su índice
fila = productsdf.loc[45]
fila

Name            Eco Vacuum Iron Phone Clean One Max
Description               Ten heart tree see movie.
Brand                     Beltran, Khan and Proctor
Category                            Office Supplies
Price                                            20
Currency                                        USD
Stock                                           397
EAN                                   1185741533846
Color                                DarkOliveGreen
Size                                       15x20 cm
Availability                               in_stock
Internal ID                                      26
Name: 45, dtype: object

In [11]:
#Filtro por condiciones
productsdf[(productsdf["Category"]=="Toys & Games")&(productsdf["Price"]<1000)]

,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
Index,,,,,,,,,,,,
19,Clean Dock Mixer Router,Democratic cost use air data push.,Matthews Ltd,Toys & Games,411,USD,202,8630605129268,Ivory,Large,discontinued,51
25,Clean Webcam Powerbank Portable Compact,Investment ability bring recognize meeting hus...,"Pearson, Hubbard and Woodward",Toys & Games,935,USD,415,8582074240015,MediumVioletRed,S,discontinued,14
31,Treadmill,Role hotel test meeting probably reduce.,"Franklin, Liu and Evans",Toys & Games,537,USD,646,3194115967840,DarkViolet,L,in_stock,93
79,Microphone Heater,Hold song fish senior expect.,Joseph-Chan,Toys & Games,200,USD,177,5317647504750,Aquamarine,XS,discontinued,85
106,Silent Fan Fast One,Week situation of air nothing cost spring.,"Hayden, Woodward and Barton",Toys & Games,969,USD,947,4987521922089,Azure,L,out_of_stock,32
153,Automatic Clock Drone Charger,Present whose teacher over born hospital.,Cunningham Group,Toys & Games,357,USD,870,3056654769340,PowderBlue,M,pre_order,40
230,Wireless Headphones Fast Lite Premium,Thus doctor page month last art practice.,"Weeks, Jensen and Andrade",Toys & Games,635,USD,360,3695066685031,DarkSlateBlue,50x70 cm,in_stock,88
233,Wireless Heater Monitor Max Clean,Guy consider career better.,"Gould, Mays and Clayton",Toys & Games,447,USD,570,6553937773171,Violet,30x40 cm,in_stock,25
422,Ultra Vacuum,Front more season no nor region dark.,Little-Hamilton,Toys & Games,287,USD,644,6446038993367,Brown,5x7 in,in_stock,31
437,Silent Dock Mixer Router Edge,Research population score music hold soldier.,Lang-Coleman,Toys & Games,805,USD,273,1633338435658,Salmon,30x40 cm,discontinued,74
468,Ultra Brush Touch Mini,Admit field language state result community.,"Massey, Stephenson and Huff",Toys & Games,145,USD,67,4835928273023,Olive,12x18 in,limited_stock,97
471,Automatic Webcam Scooter One Compact,A wrong because smile school enough.,"Larson, Mann and Guerra",Toys & Games,330,USD,832,9672063718515,LightSteelBlue,Medium,backorder,48
503,Camera Treadmill Heater,Situation grow threat run million prepare econ...,"Terry, Murray and Morse",Toys & Games,907,USD,463,1870102234035,DarkOrange,Large,pre_order,51
553,Eco Webcam Smart,Want someone rate eat.,Meza-Banks,Toys & Games,99,USD,663,881552977244,IndianRed,8x10 in,backorder,80
558,Clean Stove Iron 360 Edge Wireless,Fact fear door land fly bit role wait.,Haney Ltd,Toys & Games,930,USD,771,8856058569103,DarkOliveGreen,Extra Large,discontinued,8
572,Rechargeable Mixer Drone Toaster,Traditional hot how.,Morales-Harrington,Toys & Games,806,USD,895,4120167422470,DarkOliveGreen,XXL,in_stock,98
656,Wireless Brush Blender Vacuum,Cause television international include law nor...,"Torres, Waters and Gallagher",Toys & Games,406,USD,400,9974077678541,DarkGray,Medium,in_stock,93
692,Lock,Send decide your next whether easy.,Herring Ltd,Toys & Games,927,USD,316,5757684379612,PaleVioletRed,8x10 in,out_of_stock,31
701,Microphone Cooler,Other allow none chair none town house.,Austin Inc,Toys & Games,81,USD,85,8608922412813,Beige,Extra Large,in_stock,47
746,Smart Printer Freezer Advanced,Thus house treatment run event this level ever...,"Fernandez, Duran and James",Toys & Games,761,USD,389,6562517429032,LightSalmon,10x10 cm,in_stock,43
900,Fast Webcam Projector Lock Rechargeable,Hit cover agree good story population.,"Simpson, Atkins and Daniel",Toys & Games,448,USD,318,5608612527370,CornflowerBlue,30x40 cm,backorder,94
987,Advanced Projector Compact Sense Mini,Usually quite I floor majority couple usually.,Mcintosh Inc,Toys & Games,179,USD,106,1914304125804,Lavender,Large,backorder,66
996,Silent Router Phone Portable Automatic,Piece the fight near never once bank.,Huffman Group,Toys & Games,903,USD,737,8227581307423,MediumAquaMarine,XL,limited_stock,33
997,Digital Treadmill Clean Go,Apply drive outside reach apply.,Woodward Group,Toys & Games,8,USD,330,522633507294,PaleVioletRed,Medium,out_of_stock,9

In [12]:
productsdf.loc[productsdf["Name"]=="Microphone Cooler"]

,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
Index,,,,,,,,,,,,
191,Microphone Cooler,Pattern bad appear interview lay threat most.,"Gregory, Stanton and Dominguez",Cycling,565,USD,46,3345139264280,SandyBrown,Large,backorder,11
701,Microphone Cooler,Other allow none chair none town house.,Austin Inc,Toys & Games,81,USD,85,8608922412813,Beige,Extra Large,in_stock,47

In [13]:
#Tambien existe na forma de filtrar or Query , sirve para comprimir las condiciones a buscar
#y que estao se ueda hacer en un lenguaje más Natural
productsdf.query("Category == 'Toys & Games'")

,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
Index,,,,,,,,,,,,
19,Clean Dock Mixer Router,Democratic cost use air data push.,Matthews Ltd,Toys & Games,411,USD,202,8630605129268,Ivory,Large,discontinued,51
25,Clean Webcam Powerbank Portable Compact,Investment ability bring recognize meeting hus...,"Pearson, Hubbard and Woodward",Toys & Games,935,USD,415,8582074240015,MediumVioletRed,S,discontinued,14
31,Treadmill,Role hotel test meeting probably reduce.,"Franklin, Liu and Evans",Toys & Games,537,USD,646,3194115967840,DarkViolet,L,in_stock,93
79,Microphone Heater,Hold song fish senior expect.,Joseph-Chan,Toys & Games,200,USD,177,5317647504750,Aquamarine,XS,discontinued,85
106,Silent Fan Fast One,Week situation of air nothing cost spring.,"Hayden, Woodward and Barton",Toys & Games,969,USD,947,4987521922089,Azure,L,out_of_stock,32
153,Automatic Clock Drone Charger,Present whose teacher over born hospital.,Cunningham Group,Toys & Games,357,USD,870,3056654769340,PowderBlue,M,pre_order,40
230,Wireless Headphones Fast Lite Premium,Thus doctor page month last art practice.,"Weeks, Jensen and Andrade",Toys & Games,635,USD,360,3695066685031,DarkSlateBlue,50x70 cm,in_stock,88
233,Wireless Heater Monitor Max Clean,Guy consider career better.,"Gould, Mays and Clayton",Toys & Games,447,USD,570,6553937773171,Violet,30x40 cm,in_stock,25
422,Ultra Vacuum,Front more season no nor region dark.,Little-Hamilton,Toys & Games,287,USD,644,6446038993367,Brown,5x7 in,in_stock,31
437,Silent Dock Mixer Router Edge,Research population score music hold soldier.,Lang-Coleman,Toys & Games,805,USD,273,1633338435658,Salmon,30x40 cm,discontinued,74
468,Ultra Brush Touch Mini,Admit field language state result community.,"Massey, Stephenson and Huff",Toys & Games,145,USD,67,4835928273023,Olive,12x18 in,limited_stock,97
471,Automatic Webcam Scooter One Compact,A wrong because smile school enough.,"Larson, Mann and Guerra",Toys & Games,330,USD,832,9672063718515,LightSteelBlue,Medium,backorder,48
503,Camera Treadmill Heater,Situation grow threat run million prepare econ...,"Terry, Murray and Morse",Toys & Games,907,USD,463,1870102234035,DarkOrange,Large,pre_order,51
553,Eco Webcam Smart,Want someone rate eat.,Meza-Banks,Toys & Games,99,USD,663,881552977244,IndianRed,8x10 in,backorder,80
558,Clean Stove Iron 360 Edge Wireless,Fact fear door land fly bit role wait.,Haney Ltd,Toys & Games,930,USD,771,8856058569103,DarkOliveGreen,Extra Large,discontinued,8
572,Rechargeable Mixer Drone Toaster,Traditional hot how.,Morales-Harrington,Toys & Games,806,USD,895,4120167422470,DarkOliveGreen,XXL,in_stock,98
656,Wireless Brush Blender Vacuum,Cause television international include law nor...,"Torres, Waters and Gallagher",Toys & Games,406,USD,400,9974077678541,DarkGray,Medium,in_stock,93
692,Lock,Send decide your next whether easy.,Herring Ltd,Toys & Games,927,USD,316,5757684379612,PaleVioletRed,8x10 in,out_of_stock,31
701,Microphone Cooler,Other allow none chair none town house.,Austin Inc,Toys & Games,81,USD,85,8608922412813,Beige,Extra Large,in_stock,47
746,Smart Printer Freezer Advanced,Thus house treatment run event this level ever...,"Fernandez, Duran and James",Toys & Games,761,USD,389,6562517429032,LightSalmon,10x10 cm,in_stock,43
900,Fast Webcam Projector Lock Rechargeable,Hit cover agree good story population.,"Simpson, Atkins and Daniel",Toys & Games,448,USD,318,5608612527370,CornflowerBlue,30x40 cm,backorder,94
987,Advanced Projector Compact Sense Mini,Usually quite I floor majority couple usually.,Mcintosh Inc,Toys & Games,179,USD,106,1914304125804,Lavender,Large,backorder,66
996,Silent Router Phone Portable Automatic,Piece the fight near never once bank.,Huffman Group,Toys & Games,903,USD,737,8227581307423,MediumAquaMarine,XL,limited_stock,33
997,Digital Treadmill Clean Go,Apply drive outside reach apply.,Woodward Group,Toys & Games,8,USD,330,522633507294,PaleVioletRed,Medium,out_of_stock,9

In [14]:
#Aplicacion de una función de validacion a un DataFrame completo
def rangoIVA(precio):
  precio = precio*18
  iva = precio*0.16
  return iva<30

productsdf[productsdf["Price"].apply(rangoIVA)]

,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
Index,,,,,,,,,,,,
263,Smart Camera Router Fan Go,Always enter exist bed.,Reilly PLC,Health & Wellness,9,USD,287,6055269196883,Moccasin,100x200 mm,discontinued,69
603,Wireless Scooter Microphone,Sell source own arrive information.,Bailey Group,Sports & Outdoors,1,USD,258,3360515559200,Gainsboro,Medium,backorder,38
685,Automatic Dock,Among prepare resource evidence test no big.,Holland-Jefferson,Laptops & Computers,4,USD,134,6473931772959,BlanchedAlmond,Extra Large,in_stock,36
734,Router Freezer Webcam,Enjoy yes wear road.,Ross-Gray,Men's Clothing,7,USD,910,9897925861851,MediumOrchid,Large,backorder,78
816,Smart Heater Thermostat,Rise herself religious time care certainly his...,Lane-Mcneil,Men's Clothing,1,USD,634,5534974183476,MediumSlateBlue,Large,discontinued,11
997,Digital Treadmill Clean Go,Apply drive outside reach apply.,Woodward Group,Toys & Games,8,USD,330,522633507294,PaleVioletRed,Medium,out_of_stock,9

#TRATAMIENTO DE DATOS

In [15]:
sfy_df = pd.read_csv("spotify_global_trends.csv")
sfy_df

,track_name,artist_name,streams,stream_change,7day,genre,country,pos,days,viral_score,trend,popularity_category,longevity
0,SWIM,BTS,11273830,-3370522,25918182,K-Pop,KR,1,2,37192012,Falling,Trending,New
1,Body to Body,BTS,6815694,-4369341,18000729,K-Pop,KR,2,2,24816423,Falling,Trending,New
2,Babydoll,Dominic Fike,5733862,178968,36599831,Alternative Pop,Florida,3,119,42333693,Rising,Trending,Evergreen
3,Hooligan,BTS,5338608,-3396855,14074071,K-Pop,KR,4,2,19412679,Falling,Trending,New
4,FYA,BTS,5196767,-2873904,13267438,K-Pop,KR,5,2,18464205,Falling,Trending,New
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,The Chain - 2004 Remaster,Fleetwood Mac,1210598,-79537,8817306,Rock,GB,196,205,10027904,Falling,Average,Evergreen
174,Love On The Brain,Rihanna,1203160,-69820,7439269,Soul,US,197,352,8642429,Falling,Average,Evergreen
175,Sign of the Times,Harry Styles,1198929,-121566,3816744,Pop,England,198,331,5015673,Falling,Average,Evergreen
176,Sorry,Justin Bieber,1192146,-86760,7346804,Pop,CA,199,767,8538950,Falling,Average,Evergreen
177,Life Goes On,BTS,1191777,-76127,8979038,K-Pop,KR,200,207,10170815,Falling,Average,Evergreen

In [16]:
#Vamos a verificar si hay valores faltantes
columnas = list(sfy_df.columns)
valores_faltantes = []
for i in columnas:
   valores_faltantes.append(sfy_df[i].isna().sum())
errores = {
    "Columnas": columnas,
    "Valores faltantes": valores_faltantes
}
pd.DataFrame(errores)

               Columnas  Valores faltantes
0            track_name                  0
1           artist_name                  0
2               streams                  0
3         stream_change                  0
4                  7day                  0
5                 genre                  0
6               country                  0
7                   pos                  0
8                  days                  0
9           viral_score                  0
10                trend                  0
11  popularity_category                  0
12            longevity                  0

In [17]:
apt_df = pd.read_csv("airlines.csv")
apt_df

,airline_id,airline_name,alias,iata_code,icao_code,callsign,country,active
0,-1,Unknown,\N,-,NaN,\N,\N,Y
1,1,Private flight,\N,-,NaN,NaN,NaN,Y
2,3,1Time Airline,\N,1T,RNX,NEXTIME,South Africa,Y
3,10,40-Mile Air,\N,Q5,MLA,MILE-AIR,United States,Y
4,13,Ansett Australia,\N,AN,AAA,ANSETT,Australia,Y
...,...,...,...,...,...,...,...,...
1531,21131,All America BOPY,All America BOPY,0P,PYB,BOPY,Paraguay,Y
1532,21181,Air Andaman (2Y),NaN,2Y,AOW,AIR ANDAMAN,Thailand,N
1533,21268,Jetgo Australia,NaN,JG,NaN,NaN,Australia,Y
1534,21270,Air Carnival,NaN,2S,NaN,NaN,India,Y
1535,21317,Svyaz Rossiya,Russian Commuter,7R,SJM,RussianConnecty,Russia,Y

In [18]:
#Vamos a verificar si hay valores faltantes
columnas1 = list(apt_df.columns)
vlr_flt = []
for i in columnas1:
  vlr_flt.append(apt_df[i].isna().sum())
dat_err = {
    "Columnas": columnas1,
    "Valores Faltantes": vlr_flt
}
pd.DataFrame(dat_err)

       Columnas  Valores Faltantes
0    airline_id                  0
1  airline_name                  0
2         alias                338
3     iata_code                  2
4     icao_code                275
5      callsign                395
6       country                  9
7        active                  0

In [19]:
# Para corregir los datos faltantes la forma más sencilla es usando el método fillna
df_fill = apt_df.fillna(
    #Diccionario que funciona para solucionar las columnas con valores faltantes
   {
    "alias": "Sin alias"
   }
)
#Eliminación de filas con valores faltantes

df_fill

,airline_id,airline_name,alias,iata_code,icao_code,callsign,country,active
0,-1,Unknown,\N,-,NaN,\N,\N,Y
1,1,Private flight,\N,-,NaN,NaN,NaN,Y
2,3,1Time Airline,\N,1T,RNX,NEXTIME,South Africa,Y
3,10,40-Mile Air,\N,Q5,MLA,MILE-AIR,United States,Y
4,13,Ansett Australia,\N,AN,AAA,ANSETT,Australia,Y
...,...,...,...,...,...,...,...,...
1531,21131,All America BOPY,All America BOPY,0P,PYB,BOPY,Paraguay,Y
1532,21181,Air Andaman (2Y),Sin alias,2Y,AOW,AIR ANDAMAN,Thailand,N
1533,21268,Jetgo Australia,Sin alias,JG,NaN,NaN,Australia,Y
1534,21270,Air Carnival,Sin alias,2S,NaN,NaN,India,Y
1535,21317,Svyaz Rossiya,Russian Commuter,7R,SJM,RussianConnecty,Russia,Y

In [20]:
column = list(df_fill.columns)
vlr_flt1 = []
for i in column:
  vlr_flt1.append(df_fill[i].isna().sum())
dat_err1 = {
    "Columnas": column,
    "Valores Faltantes": vlr_flt1
}
pd.DataFrame(dat_err1)

       Columnas  Valores Faltantes
0    airline_id                  0
1  airline_name                  0
2         alias                  0
3     iata_code                  2
4     icao_code                275
5      callsign                395
6       country                  9
7        active                  0

In [21]:
#Eliminación de filas con valores faltantes